# Generated by Django 6.0.3 on 2026-03-12 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('ancho_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('alto_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('area_m2', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carritoitems',
                'unique_together': {('usuario', 'producto', 'ancho_cm', 'alto_cm')},
            },
        ),
    ]
