# Generated by Django 6.0.3 on 2026-03-12 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('cufe', models.CharField(max_length=255, unique=True)),
                ('xml_path', models.URLField(blank=True, max_length=255, null=True)),
                ('pdf_path', models.URLField(blank=True, max_length=255, null=True)),
                ('enviada_dian', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('transmitida', 'Transmitida'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='generada', max_length=50)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
    ]
