# Generated by Django 6.0.3 on 2026-03-12 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('departamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estadospedido',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciudad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='pedidos.departamento')),
            ],
            options={
                'db_table': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=150, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.ciudad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='usuarios.cliente')),
            ],
            options={
                'db_table': 'direcciones',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='usuarios.cliente')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.direccion')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pedidos.estadopedido')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('historial_id', models.AutoField(primary_key=True, serialize=False)),
                ('cambiado_en', models.DateTimeField(auto_now_add=True)),
                ('notas_cambio', models.TextField(blank=True, null=True)),
                ('cambiado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.estadopedido')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'historialestadospedido',
                'ordering': ['-cambiado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('ancho_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('alto_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('area_m2', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precio_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'detallepedido',
            },
        ),
    ]
