# Generated by Django 6.0.3 on 2026-03-12 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionAdmin',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('destinatario', models.EmailField(max_length=150)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('intentos', models.IntegerField(default=1)),
                ('error_detalle', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'notificacionesadmin',
            },
        ),
    ]
